version: '3.8'

services:
  server-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    image: damianomiazzi/multiarch-server:latest
    ports:
      - "3002:3002"
    env_file:
      - .env

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: damianomiazzi/multiarch-postgres:latest
    container_name: postgres_container
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: amu_db
    ports:
      - "5432:5432"

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    image: damianomiazzi/multiarch-pgadmin:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
    external: true