version: "3"
services:
  server-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    #depends_on:
    #  - db
    # environment:
    #   - PORT=3000
     # - DATABASE_URL=postgres://postgres:password@db:5432/db
    env_file:
     - .env